### ISSUE TITLE
Can GT be used to search for repos by keyword?

### ISSUE THREAD

**Issue by SamyBencherif** [blue-9/github-trending#1]
Hello cyblue9,

This is an awesome project. It is making a great addition to my CLI only lifestyle. 

I find Github to be a great place to find open source shell programs. so naturally the next step for me would be to browse Github itself from the command line. 

Although this somewhat goes against the project title, I am wondering if it is possible to use this app to search for repos by keyword sometimes instead of by trending?

If it is not yet possible, do you have any quick advice how a new contributor might implement this in a fork?

Thanks in advance!
-S

**Comment by cyblue9** [comment]
Hi @SamyBencherif !

Thank you for your comment!

Is [this](https://github.com/donnemartin/gitsome/blob/master/COMMANDS.md#gh-search-repos) the CLI tool that you want to find?


If you will fork this repo and implement, I will some advice.😀

**Comment by SamyBencherif** [comment]
@cyblue9 That looks very promising. Thank you for your prompt reply.
